# The URL the site will be built for
base_url = "https://marcloehe.de/"

theme = "lightspeed"
title = "Marc Löhe"
description ="Notebook on code & software design"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "zenburn"

[extra]
# Put all your custom variables here

author = "Marc Löhe"

footer_links = [
  {url = "https://zirk.us/@bfncs", name = "Mastodon"},
  {url = "https://github.com/bfncs", name = "Github"},
]
zola = false
maintained_with_love = false
